apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-claim
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
