kind: Pod
apiVersion: v1
metadata:
  name: efs-pod-example
spec:
  containers:
  - name: the-container
    image: nginx
    volumeMounts:
      - name: efs-pvc-volume
        mountPath: "/usr/share/nginx/html"
  restartPolicy: "Never"
  volumes:
    - name: efs-pvc-volume
      persistentVolumeClaim:
        claimName: efs-pvc
