apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-test-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-direct
  nfs:					#Replace this with your NFS server details
    path: /mnt/nfs_shares/k8s   
    server: 10.0.2.9
